name = "nataliegwinters-listings"
compatibility_date = "2025-03-03"
main = "index.js"

[[r2_buckets]]
binding = "LISTINGS_BUCKET"
bucket_name = "all-listings"
preview_bucket_name = "all-listings-preview"

# Routes for listings API
routes = [
  { pattern = "nataliegwinters.com/api/listings/*", zone_name = "nataliegwinters.com" },
  { pattern = "www.nataliegwinters.com/api/listings/*", zone_name = "nataliegwinters.com" }
] 