name = "nataliegwinters"
compatibility_date = "2025-03-03"
[build]
command = ""
output_dir = "public"
[[r2_buckets]]
binding = "LISTINGS_BUCKET"
bucket_name = "all-listings"
preview_bucket_name = "all-listings-preview"
[site]
bucket = "public"