name = "business-listings"
type = "javascript"

# Path to your worker script
main = "business-listings/worker.js"  # Adjust this to the correct relative path

[[kv_namespaces]]
binding = "BUSINESS_LISTINGS_KV"
id = "${CF_KV_NAMESPACE_ID}"
