name = "business-listings-worker"

main = "src/index.ts"  # Path to your entry script (adjust if using JS)

[build]
command = "npm install && npm run build"  # If you have a build step

[site]
bucket = "./templates"  # Folder where your static files (templates) are stored

[env.production]
route = "https://nataliegwinters.com.com/*"
zone_id = "34246ddf997608f8590474fcb874e548"

[[kv_namespaces]]
binding = "BUSINESS_LISTINGS"
id = "${BUSINESS_LISTINGS_NAMESPACE_ID}"  # Use the environment variable for the ID
