name = "business-listings"
type = "javascript"

[[kv_namespaces]]
binding = "BUSINESS_LISTINGS_KV"
id = "${CF_KV_NAMESPACE_ID}"

main = "business-listings/worker.js"

compatibility_date = "2025-03-01"  # Add this line with your preferred date
