name = "nataliegwinters"
compatibility_date = "2025-03-03"
main = "functions/main.js"

# R2 bucket for business listings
[[r2_buckets]]
binding = "LISTINGS_BUCKET"
bucket_name = "all-listings"
preview_bucket_name = "all-listings-preview"

# R2 bucket for news articles
[[r2_buckets]]
binding = "ARTICLES_BUCKET"
bucket_name = "all-articles"
preview_bucket_name = "all-articles-preview"

# Static site assets
[site]
bucket = "public"

# Routes for all content
routes = [
  { pattern = "nataliegwinters.com", zone_name = "nataliegwinters.com" },
  { pattern = "nataliegwinters.com/*", zone_name = "nataliegwinters.com" },
  { pattern = "www.nataliegwinters.com", zone_name = "nataliegwinters.com" },
  { pattern = "www.nataliegwinters.com/*", zone_name = "nataliegwinters.com" }
]