# wrangler.toml
name = "business-listings-worker"
compatibility_date = "2025-03-03"

[[r2_buckets]]
binding = "LISTINGS_BUCKET"
bucket_name = "all-listings"
preview_bucket_name = "all-listings-preview"