name = "nataliegwinters-main"
compatibility_date = "2025-03-03"
main = "index.js"

[site]
bucket = "public"

# Routes for main site content
routes = [
  { pattern = "nataliegwinters.com", zone_name = "nataliegwinters.com" },
  { pattern = "nataliegwinters.com/*", zone_name = "nataliegwinters.com" },
  { pattern = "www.nataliegwinters.com", zone_name = "nataliegwinters.com" },
  { pattern = "www.nataliegwinters.com/*", zone_name = "nataliegwinters.com" }
]

# Exclude paths handled by other workers
[rules]
[rules.exclude]
paths = [
  "/api/articles/*",
  "/api/listings/*"
] 