name: Run Scraper Script

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Updated to latest version

    - name: Set up Node.js
      uses: actions/setup-node@v4  # Updated to latest version
      with:
        node-version: '18'  # Use latest LTS version

    - name: Ensure package.json exists
      run: |
        if [ ! -f package.json ]; then
          echo "package.json missing! Creating one..."
          npm init -y
        fi

    - name: Install dependencies
      run: npm install  # Install dependencies

    - name: Run scraper script
      run: node scraper.js  # Run the scraper script

    - name: Commit and push changes
      run: |
        git config --global user.name "meeeeeooooowwwwwww"
        git config --global user.email "ruckus@americafirst.co.nz"
        git add news.html
        git commit -m "Updated news.html from scraper" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/meeeeeooooowwwwwww/nataliegwinters.git HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Authenticate with GitHub token
