name: Scrape and Update Warroom Videos

on:
  schedule:
    - cron: '0 */12 * * *' # Run every 12 hours
  push:
    branches:
      - main # Runs when changes are pushed to the main branch

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Make sure to specify the version you need

    # Install required dependencies (make sure you have a requirements.txt in your repo)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run the scraper script
    - name: Run Scraper Script
      run: |
        python warroom-videos-updater/warroom_video_updater.py # Replace with the actual path of your script

    # Commit and push updated warroom-videos.json
    - name: Commit and push updated warroom-videos.json
      run: |
        git config --global user.email "youremail@example.com"
        git config --global user.name "Your Name"
        git add warroom-videos-updater/warroom-videos.json  # Replace with the actual path of your json file
        git commit -m "Update warroom-videos.json"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
