name: Update Sitemap

on:
  push:
    branches:
      - main  # This will run the action on pushes to the 'main' branch
  schedule:
    - cron: "0 0 * * *"  # Runs the action every day at midnight UTC

jobs:
  update-sitemap:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu environment
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # This action checks out the repository's code
      
    - name: Set up Python
      uses: actions/setup-python@v2  # This action sets up Python
      with:
        python-version: '3.x'  # You can specify the Python version to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 jinja2  # Install the necessary packages
    
    - name: Run the sitemap update script
      run: |
        python path/to/update_sitemap.py  # Adjust the path to the script location
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Provides GitHub token for any necessary authentication

    - name: Commit and push updated sitemap.xml
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add sitemap.xml
        git commit -m "Update sitemap.xml"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for pushing changes back to the repository
